apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # serviceAccountName: api-service-account
      # initContainers:
      # - name: init-permissions
      #   image: busybox
      #   command: ['sh', '-c', 'chmod -R 755 /app && chmod -R 755 /app/node_modules/.bin']
      #   volumeMounts:
      #   - name: app-volume
      #     mountPath: /app    
      containers:
      - name: frontend
        # image: docker0now/react:latest
        # image: host.minikube.internal:5000/react:latest
        image: local-registry:5001/react:latest
        # image: nginx:latest
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-volume
          mountPath: /usr/share/nginx/html
        command: ['sh', '-c', 'nginx -g "daemon off;"']
        securityContext:
          runAsGroup: 0
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: frontend-pvc