apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:          
        runAsUser: 0
      # initContainers:
      # - name: init-chown-docker
      #   image: alpine
      #   command: ['sh', '-c', 'apk add --no-cache shadow; addgroup -g 999 docker; add user jenkins docker']
      # # - name: init-jenkins
      # #   image: alpine
      # #   # command: ['sh', '-c', 'chown :999 /var/run/docker.sock; chmod 660 /var/run/docker.sock; chmod -R 777 /var/jenkins_home']
      # #   command: ['sh', '-c', 'chown :docker /var/run/docker.sock']
      #   securityContext:
      #       runAsUser: 0
      #   volumeMounts:
      #     - name: docker-sock
      #       mountPath: /var/run/docker.sock
      # serviceAccountName: jenkins-admin
      containers:
      - name: jenkins
        image: local-registry:5000/jenkins/jenkins
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        env:
        # env
        # - name: JENKINS_URL
        #   value: http://localhost:8080/jenkins/
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        securityContext:
            runAsUser: 0
            runAsGroup: 0
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        # livenessProbe:
        #   httpGet:
        #     path: "/login"
        #     port: 8080
        #   initialDelaySeconds: 90
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 5
        # readinessProbe:
        #   httpGet:
        #     path: "/login"
        #     port: 8080
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 3
        volumeMounts:
          - name: jenkins-mnt
            mountPath: /var/jenkins_home
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-mnt
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
