FROM tomcat:latest

ARG TOMCAT_ROOT=/usr/local/tomcat/
ARG WEBAPPS_ROOT=${TOMCAT_ROOT}/webapps
ARG WAR_FILE=Backend.war

RUN apt-get update && apt-get install -y unzip

# 새로운 react 폴더를 생성하고 build 폴더 복사
RUN rm -rf ${WEBAPPS_ROOT} && \
    mv ${WEBAPPS_ROOT}.dist ${WEBAPPS_ROOT} 

# 권한 및 context 설정
COPY ./docker/tomcat-users.xml ${TOMCAT_ROOT}/conf/
COPY ./docker/context.xml ${WEBAPPS_ROOT}/manager/META-INF/

# 수정된 패키지 복사
COPY ./Backend/build/libs/${WAR_FILE} /tmp

# 서버 배포 및 임시파일 삭제
RUN mkdir -p ${WEBAPPS_ROOT}/demo && \
    unzip /tmp/${WAR_FILE} -d ${WEBAPPS_ROOT}/demo && \
    rm /tmp/${WAR_FILE}
    
EXPOSE 8080

CMD ["catalina.sh", "run"]