services:
    react:
        image: local-registry:5000/react
        build:
            context: ..
            dockerfile: ./docker/Dockerfile-fe
            
        container_name: frontend-react
        ports:
            - "3000:80"
        # volumes:
            # - "..:/app"
        networks:
            - mynetwork
networks:
    mynetwork:
        # external: true