# Jenkins LTS 이미지 기반
FROM jenkins/jenkins:lts

# root 권한을 사용하도록 설정
USER root

# APT 기본 설정
RUN apt-get clean && \
    apt-get update

# 필수 패키지 설치 (JDK, Docker, Git)
# RUN apt-get update && apt-get install -y openjdk-17-jdk curl git docker.io
# Docker CLI 설치
RUN apt-get update && \
    apt-get -y install apt-transport-https \
      ca-certificates \
      curl \
      gnupg2 \
      software-properties-common && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/debian \
      $(lsb_release -cs) \
      stable" && \
    apt-get update && \
    apt-get -y install docker-ce-cli

  # Node.js 및 npm 설치
  RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
      apt-get install -y nodejs
  
  COPY ./Frontend/package.json .
  COPY ./Frontend/package-lock.json .
  RUN npm install

# APT 캐시 정리
RUN rm -rf /var/lib/apt/lists/*

# docker 그룹에 jenkins 사용자 추가
RUN usermod -aG systemd-journal jenkins
RUN chmod -R 777 /var/run

# 포트 설정
EXPOSE 8080
EXPOSE 50000

# 유저 전환
USER jenkins

# Jenkins 시작
ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]