apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: default
type: Opaque  # Secret 타입 지정
data:
  MYSQL_ROOT_PASSWORD: dmVyeXNlY3JldA==
  MYSQL_DATABASE: bXlkYg==
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: c2VjcmV0
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson  # Secret 타입 지정
data:
  .dockerconfigjson: eyJhdXRocyI6eyJob3N0Lm1pbmlrdWJlLmludGVybmFsOjUwMDAiOnsidXNlcm5hbWUiOiJkb2NrZXIiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiZW1haWwiOiJjNG5vd0BuYXZlci5jb20iLCJhdXRoIjoiWkc5amEyVnlPbkJoYzNOM2IzSmsifX19