apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: default
type: Opaque  # Secret 타입 지정
data:
  MYSQL_ROOT_PASSWORD: dmVyeXNlY3JldA==
  MYSQL_DATABASE: bXlkYg==
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: c2VjcmV0
---
apiVersion: v1
kind: Secret
metadata:
  name: local-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson  # Secret 타입 지정
data:
  .dockerconfigjson: eyJhdXRocyI6eyJsb2NhbC1yZWdpc3RyeTo1MDAxIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6ImFkbWluIiwiZW1haWwiOiJjNG5vd0BuYXZlci5jb20iLCJhdXRoIjoiWVdSdGFXNDZZV1J0YVc0PSJ9fX0=